// Code generated by entc, DO NOT EDIT.

package ent

import (
	"MyApp/internal/app/pkg/ent/article"
	"MyApp/internal/app/pkg/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	articleFields := schema.Article{}.Fields()
	_ = articleFields
	// articleDescCreatedTime is the schema descriptor for created_time field.
	articleDescCreatedTime := articleFields[3].Descriptor()
	// article.DefaultCreatedTime holds the default value on creation for the created_time field.
	article.DefaultCreatedTime = articleDescCreatedTime.Default.(func() time.Time)
}
