// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package app

import (
	"MyApp/internal/app/api"
	"MyApp/internal/app/biz"
	"MyApp/internal/app/data"
	"MyApp/internal/app/router"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, func(), error) {
	client, cleanup, err := InitEntOrm()
	if err != nil {
		return nil, nil, err
	}
	modelArticle := &data.ModelArticle{
		DB: client,
	}
	article := biz.Article{
		ModelArticle: modelArticle,
	}
	apiArticle := &api.Article{
		ArticleBiz: article,
	}
	routerRouter := &router.Router{
		ArticleAPI: apiArticle,
	}
	engine := InitGinEngine(routerRouter)
	injector := &Injector{
		Engine: engine,
	}
	return injector, func() {
		cleanup()
	}, nil
}
